### ISSUE TITLE
針對400的問題列出解決方案

### ISSUE THREAD

**Issue by yaodehaung** [bellalo12/smart_brain_api#2]
方向:
1. 在本機端是否有用pg database測過
2. 如果第一個選項可以接下來換用postman測
3. 二三沒問題就開始是heroku的設定問題

**Comment by bellalo12** [comment]
在使用heroku前已用1、2測試過沒問題。
所以問題應該是出現在heroku的設定，我已經新增procfile，但問題仍然存在！
如果是第一次使用heroku的話，process.env的部分有特別需要設定什麼嗎？
const db = knex({
  client: 'pg',
  connection: {
    connectinString : process.env.DATABASE_URL,
    ssl: true,
  }
});

然後heroku config 有 DATABASE_URL: postgres://wezwijdwrhhhpb:ef1a222fa5b897f23a1f816ebc916b7bd1834a1c09d98387e1c0e51d9af65b03@ec2-54-83-204-6.compute-1.amazonaws.com:5432/d3epmn2s7vtnpa

**Comment by yaodehaung** [comment]
我已經明白你的狀況，我這幾點幫你測。 還會在issue這邊幫你提出解決方案

**Comment by yaodehaung** [comment]
你有在database建立table嗎？？
我看到你的程式裡面沒有建立資料庫的table，只有建立資料庫連接而已。

**Comment by bellalo12** [comment]
我有在database裡建立 users 和 login 兩個 table ，使用heroku pg:psql  \d 有出現
radiant-stream-63004::DATABASE=> \d
                 List of relations
 Schema |     Name     |   Type   |     Owner      
--------+--------------+----------+----------------
 public | login        | table    | wezwijdwrhhhpb
 public | login_id_seq | sequence | wezwijdwrhhhpb
 public | users        | table    | wezwijdwrhhhpb
 public | users_id_seq | sequence | wezwijdwrhhhpb
(4 rows)

radiant-stream-63004::DATABASE=> SELECT * FROM login;
 id | hash | email 
----+------+-------
(0 rows)

radiant-stream-63004::DATABASE=> SELECT * FROM users;
 id | name | email | entries | joined 
----+------+-------+---------+--------
(0 rows)

**Comment by yaodehaung** [comment]
那可以以print出裡面的資料嗎？？
